[package]
name = "isomage"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "isomage"
path = "src/main.rs"

[lib]
name = "isomage"
path = "src/lib.rs"

[dependencies]
byteorder = "1.4"

[profile.release]
opt-level = 1
lto = false
codegen-units = 16
